### ISSUE TITLE
Add relevant runtime checks

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/distributive-rpm#2]
Once #1 is resolved, we need to think about how to improve these checks beyond just what should be present at installation. We should consider what these services actually do, and add more specific/granular checks (e.g. is the port that this service runs on open?). 

 - [ ] chronos
 - [ ] collectd
 - [ ] common
 - [ ] consul
 - [ ] consul-template
 - [ ] dnsmasq
 - [ ] docker
 - [ ] handlers
 - [ ] haproxy
 - [ ] logrotate
 - [ ] logstash
 - [ ] marathon
 - [ ] mesos
 - [ ] nginx
 - [ ] vault
 - [ ] zookeeper

**Comment by noahjl** [comment]
Working ZooKeeper checks

**Comment by noahjl** [comment]
talking with @LeeLammert it seems we may still have an issue with the repoExists check for yum. Re-opening ciscocloud/distributive #30

**Comment by LeeLammert** [comment]
I only see repo checks for chronos, marathon, mesos - should there not be more?
