### ISSUE TITLE
Add %post{un} script to distributive.spec file

### ISSUE THREAD

**Issue by noahjl** [CiscoCloud/distributive-rpm#3]
To remove the need for ansible or additional packages we can run a %post script in in the spec file that will allow us to check for roles that exist on install, and install check definitions accordingly. 

**Info needed:** a consistent way to validate what roles are installed on a node. 

**Requirement:** A %post script should only use sh and possibly GNU coreutils in best practice (when linux is the target) 

**Pseudo-though:** 
```bash
roleChk=${ #tests for each roles' existence}
case $roleChk in
    consul) 
        echo $edits >> file.json
        cp -p %{_datadir}/%{name}/consul.json /etc/distributive/
        echo "Installed consul distributive checks"
    ;;&
   docker) 
       repeat above... 
    ;;&
.....
esac
```

**Comment by siddharthist** [comment]
Distributive is installed as part of the common role, which is before all the others. Do you suggest we decouple this? I don't really know how it might work otherwise.

**Comment by noahjl** [comment]
Agreed in that case. No post install tasks identified for distributive.
