### ISSUE TITLE
http/https match string check

### ISSUE THREAD

**Issue by LeeLammert** [CiscoCloud/distributive-rpm#4]
It would be very nice to have a check that would match a string via http/https - e.g. "Running" for the Marathon UI, to simple status checks via the a webUI.

**Comment by siddharthist** [comment]
@LeeLammert This should go on the Distributive repo, rather than distributive-rpm. I'll go ahead and recreate this issue there.

**Comment by LeeLammert** [comment]
May have an issue with certificate validation:

2015/06/22 17:42:34 Couldn't read file:
	Path: https://localhost:8080
	Error: Get https://localhost:8080: x509: certificate is valid for *.service.consul, not localhost

Should we have a way to fake it for testing with a vagrant VM?

**Comment by siddharthist** [comment]
I'll get to work on it soon. [Here's the issue](https://github.com/CiscoCloud/distributive/issues/39)

**Comment by LeeLammert** [comment]
On Mon, 22 Jun 2015, Langston Barrett wrote:

> I'll get to work on it soon. [Here's the issue](https://github.com/CiscoCloud/distributive/issues/39)
>
No worries, .. comment added.

	Lee
